//! The documents Rill hands an agent, generated by Rill.
//!
//! # Why this exists here
//!
//! In the reference implementation these documents are generated in the TypeScript repository
//! (`rill-backend/src/features/mcp/skill-doc.ts` and `agent-instructions.ts`), which this
//! repository specifies itself against but shares no code with. Three consequences, all of them
//! live at once:
//!
//! - The enforcement correction could not reach them. `agent-instructions.ts` heads its guardrail
//!   section "Guardrails the wallet enforces on-chain" and then lists every rule under it,
//!   including the recipient allowlist, the asset scope and the protocol scope. Nothing on the
//!   chain checks any of those.
//! - The configured base URL could not be interpolated. Those generators read their own
//!   deployment's configuration, so the endpoint they printed was whatever host the TypeScript
//!   service was running on, and a reader who pasted it reached a server that is not this one.
//! - The install line named `eseslabs/rill`, which redirects to the TypeScript specification and
//!   will never carry a binary built from this source. Following it downloaded an error page and
//!   made it executable.
//!
//! So the generator lives beside the configuration and the producers it has to agree with, and the
//! server serves what it generates.
//!
//! # Nothing here is typed out twice
//!
//! Every load-bearing string is read from the one thing that owns it: URLs from
//! [`Config::public_base_url`](crate::state::Config), the install origin and asset filenames from
//! [`rill_core::release`], the tool names from [`rill_mcp::tools`], and every enforcement label
//! from [`RuleKind::enforcement`]. A label written here as a word would be the exact defect U1
//! removed from the wallet read, one document further from the code.
//!
//! The reference's two documents are one here. `skill.md` differs from the instructions there by a
//! per-action parameter table and a REST `curl`, and this server has neither: build parameters are
//! one open object on `rill_build_action`, and there is no REST build route to name. Emitting both
//! would be two spellings of one document, which is the drift this module exists to end.
//! `fixtures/reference-doc-sections.json` records the reference's section structure and what
//! happened to each section here, and `bins/rill-server/tests/generated_docs.rs` checks it.

use axum::extract::{Path, State};
use axum::http::{header, StatusCode};
use axum::response::{IntoResponse, Response};
use rill_core::manifest::{to_declaration, CapabilityManifest, RuleKind};
use rill_core::release::{CHECKSUM_SUFFIX, LATEST_DOWNLOAD_URL, RELEASE_REPO, WALLET_ASSETS};
use rill_mcp::{Surface, Tool};
use rill_store::{PublishedSkill, SkillStore};

use crate::envelope::api_err;
use crate::state::{AppState, Config};

/// OpenCode's own configuration schema. The one URL in this module that is neither this
/// deployment's nor the release origin's, named here rather than inline so the test that forbids a
/// literal host has one place to allow and everything else to refuse.
const OPENCODE_SCHEMA_URL: &str = "https://opencode.ai/config.json";

/// `GET /api/docs`: the document with no action in it.
///
/// Also the address `GET /mcp` redirects a browser to. That redirect was written before anything
/// answered here, so until now the one link the endpoint hands a curious reader was a 404.
pub async fn docs(State(state): State<AppState>) -> Response {
    markdown(agent_instructions(&state.config, None, None))
}

/// `GET /api/skills/{id}/instructions.md`: the same document, scoped to one published action.
///
/// The path is the one the reference's `skill.md` already advertises, so links written by the
/// deployed frontend keep resolving.
pub async fn skill_instructions(State(state): State<AppState>, Path(id): Path<String>) -> Response {
    match state.skills.get(&id) {
        // No manifest: nothing in the store carries one yet. When an owner's grant is recorded
        // against a published action, this is the call that renders it, and the honest
        // no-wallet-binding state below is what a reader gets until then.
        Some(skill) => markdown(agent_instructions(&state.config, Some(&skill), None)),
        None => api_err(StatusCode::NOT_FOUND, "Skill not found"),
    }
}

/// Markdown, with the content type that makes a browser show it as text rather than download it.
fn markdown(body: String) -> Response {
    (
        [(header::CONTENT_TYPE, "text/markdown; charset=utf-8")],
        body,
    )
        .into_response()
}

/// One numbered step of the document: a heading and its lines.
///
/// Numbered at render time rather than written into the headings, because one section appears only
/// when there is a grant to describe and hand-numbered headings would renumber themselves wrongly.
struct Step {
    heading: &'static str,
    lines: Vec<String>,
}

/// The document a reader is told to paste to their agent.
///
/// `skill` names one published action when the document is fetched for one. `manifest` is the
/// owner's grant when it is known; absent, the document says so rather than describing limits that
/// are not attached, which is the only honest answer and not a detail: an agent told it is bounded
/// when it is not will act as though something will stop it.
pub fn agent_instructions(
    config: &Config,
    skill: Option<&PublishedSkill>,
    manifest: Option<&CapabilityManifest>,
) -> String {
    let endpoint = config.resource();
    let network = config.network.as_str();
    let binary = rill_core::release::WALLET_BINARY;

    let mut out: Vec<String> = vec![
        "# Rill: set up and run".into(),
        String::new(),
        "Paste this whole file to your coding agent and tell it to follow it. The agent installs \
         the local signer, connects both MCP servers, and hands back one address for you to fund. \
         After that you prompt."
            .into(),
        String::new(),
        format!(
            "- Network: **{network}**\n\
             - Build endpoint, keyless: `{endpoint}`\n\
             - Signer: `{binary}`, installed below, on your machine, holding the only key involved"
        ),
        String::new(),
        "Rill's server compiles a transaction, simulates it, and hands it back unsigned. It holds \
         no key, so the worst a compromised endpoint can propose is something your signer then \
         refuses. This document is generated by that same server, so the URLs below are this \
         deployment's own and the enforcement labels are the ones its code computes."
            .into(),
    ];

    if let Some(skill) = skill {
        out.push(String::new());
        out.push(format!(
            "Action: **{}** (`{}`). {}",
            skill.name, skill.id, skill.description
        ));
    }

    let steps = [
        install_step(),
        connect_step(&endpoint, network),
        tool_order_step(skill),
        Some(layers_step()),
        grant_step(manifest),
        prompt_step(manifest),
    ];

    for (index, step) in steps.into_iter().flatten().enumerate() {
        out.push(String::new());
        out.push(format!("## {}. {}", index + 1, step.heading));
        out.push(String::new());
        out.extend(step.lines);
    }

    out.push(String::new());
    out.extend(keyless_check(config));
    out.push(String::new());
    out.join("\n")
}

/// Step one: the binary, from the one origin that publishes it.
///
/// The first asset's block is shown in full and the others are named, rather than three blocks, so
/// a reader copies four lines instead of choosing between twelve. Which asset is first is the
/// workflow's matrix order, not a judgement made here.
fn install_step() -> Option<Step> {
    let first = WALLET_ASSETS[0];
    let others: Vec<String> = WALLET_ASSETS[1..]
        .iter()
        .map(|asset| format!("{} is `{}`", asset.platform, asset.file))
        .collect();
    let binary = rill_core::release::WALLET_BINARY;

    Some(Step {
        heading: "Install the local signer",
        lines: vec![
            format!(
                "One file per platform, no repository clone and no toolchain. Download the one \
                 for your machine, check it against the checksum published beside it, and keep the \
                 name `{binary}`. For {}:",
                first.platform
            ),
            String::new(),
            "```bash".into(),
            format!("curl -fsSLO {LATEST_DOWNLOAD_URL}/{}", first.file),
            format!(
                "curl -fsSLO {LATEST_DOWNLOAD_URL}/{}{CHECKSUM_SUFFIX}",
                first.file
            ),
            format!("shasum -a 256 -c {}{CHECKSUM_SUFFIX}", first.file),
            format!("chmod +x {file} && mv {file} {binary}", file = first.file),
            format!("./{binary} --status"),
            "```".into(),
            String::new(),
            format!(
                "The same commands with the filename swapped for another platform: {}.",
                others.join("; ")
            ),
            String::new(),
            format!(
                "Every file comes from a tag on `{RELEASE_REPO}`, the one origin that publishes \
                 this binary. An install line naming any other repository is wrong whatever else \
                 it gets right, and there are such lines in circulation."
            ),
            String::new(),
            format!(
                "`--status` prints `{binary}` and then whether it can sign. With no key it says \
                 `not ready` and exits 1, which is the expected answer on a fresh machine rather \
                 than a failed download, and its reason line says what it looked in and what to \
                 set. The key comes from the shell that launches the agent or from the `sui` CLI's \
                 own keystore, never from an argument, from MCP configuration, or from this \
                 document."
            ),
        ],
    })
}

/// Step two: both servers, and the restart that makes them visible.
fn connect_step(endpoint: &str, network: &str) -> Option<Step> {
    let binary = rill_core::release::WALLET_BINARY;
    Some(Step {
        heading: "Connect both MCP servers",
        lines: vec![
            "Claude Code, run from the directory holding the binary:".into(),
            String::new(),
            "```bash".into(),
            format!("claude mcp add --transport http rill-actions \"{endpoint}\""),
            format!(
                "claude mcp add --env \"SUI_NETWORK={network}\" --transport stdio {binary} -- \
                 \"$PWD/{binary}\""
            ),
            "```".into(),
            String::new(),
            "OpenCode, in `opencode.json` in the project root:".into(),
            String::new(),
            "```json".into(),
            "{".into(),
            format!("  \"$schema\": \"{OPENCODE_SCHEMA_URL}\","),
            "  \"mcp\": {".into(),
            format!(
                "    \"rill-actions\": {{ \"type\": \"remote\", \"url\": \"{endpoint}\", \
                 \"enabled\": true }},"
            ),
            format!(
                "    \"{binary}\": {{ \"type\": \"local\", \"command\": [\"./{binary}\"], \
                 \"environment\": {{ \"SUI_NETWORK\": \"{network}\" }}, \"enabled\": true }}"
            ),
            "  }".into(),
            "}".into(),
            "```".into(),
            String::new(),
            "Then restart the agent fully, in this directory. MCP servers are read once at \
             startup and never mid-session, so a connector added to a running agent is invisible \
             to it."
                .into(),
            String::new(),
            "The remote endpoint wants an OAuth 2.1 access token. A client that follows discovery \
             registers itself and authorizes without being configured, which for an interactive \
             client is one visit to a browser. Nothing in that flow hands the server a key, \
             because there is no key in it to hand over."
                .into(),
        ],
    })
}

/// Step three: the order, with every tool name read from the producer.
///
/// The reference document names `execute_rill_action`, `signer_status`, `create_run_set` and
/// `request_faucet`. None of those exists on either surface here, so an agent following it calls
/// four tools that are not there. Reading the names from [`rill_mcp::tools`] is what makes that
/// impossible rather than unlikely.
fn tool_order_step(skill: Option<&PublishedSkill>) -> Option<Step> {
    let remote = rill_mcp::tools(Surface::Actions);
    let local = rill_mcp::tools(Surface::Wallet);
    let hand_off = envelope_tool(&local);

    let mut lines = vec![
        "Every tool named below is read from this server's own definitions rather than written \
         into this document: the remote ones are what `tools/list` answers, and the local ones are \
         what the signer answers on stdio."
            .into(),
        String::new(),
        "Remote, on `rill-actions`, which holds no key:".into(),
        String::new(),
    ];

    let mut step = 0;
    for tool in &remote {
        step += 1;
        let mut line = format!("{step}. `{}`: {}", tool.name, summary(tool));
        if let (Some(skill), true) = (skill, takes_action_id(tool)) {
            line.push_str(&format!(" Pass `actionId` `{}`.", skill.id));
        }
        lines.push(line);
    }

    lines.push(String::new());
    lines.push("Local, on the signer, which holds the key:".into());
    lines.push(String::new());

    match hand_off {
        Some(tool) => {
            step += 1;
            lines.push(format!(
                "{step}. `{}`: {} Only this call produces a signature.",
                tool.name,
                summary(tool)
            ));
        }
        // Rendering a step that names nothing would be worse than leaving it out: an agent cannot
        // call a tool the document failed to name, and the test asserts the step is here.
        None => lines.push(
            "The signer takes the envelope and submits it. Its tool list is below; no other tool \
             anywhere can produce a signature."
                .into(),
        ),
    }

    let rest: Vec<&Tool> = local
        .iter()
        .filter(|tool| Some(tool.name.as_ref()) != hand_off.map(|t| t.name.as_ref()))
        .collect();
    if !rest.is_empty() {
        lines.push(String::new());
        lines.push("The signer also answers:".into());
        lines.push(String::new());
        for tool in rest {
            lines.push(format!("- `{}`: {}", tool.name, summary(tool)));
        }
    }

    lines.push(String::new());
    lines.push(
        "A refusal at the last step is the system working. Read what it objected to and change \
         that; the same envelope sent again earns the same refusal, and a retry after a success \
         sends a second payment."
            .into(),
    );

    Some(Step {
        heading: "Call the tools in this order",
        lines,
    })
}

/// Step four: which layer holds which limit, for every rule kind there is.
///
/// Every label and every sentence about who refuses comes from the producer. This is the section
/// the reference gets wrong: it heads the same material "Guardrails the wallet enforces on-chain"
/// and lists the pre-flight rules underneath, which tells an owner the chain is holding a recipient
/// allowlist it has never heard of.
fn layers_step() -> Step {
    let mut lines = vec![
        "An agent wallet carries rules. Which layer holds a rule decides what happens when it is \
         breached, and the two answers are not interchangeable:"
            .into(),
        String::new(),
        "| Rule | Layer | What refuses |".into(),
        "|---|---|---|".into(),
    ];

    for kind in RuleKind::all() {
        let enforcement = kind.enforcement();
        lines.push(format!(
            "| `{}` | {} | {} |",
            kind.module(),
            enforcement.as_str(),
            enforcement.enforced_by()
        ));
    }

    lines.extend([
        String::new(),
        "The on-chain rules are proved by Move against the transaction as it runs. Nothing in the \
         builder, nothing an agent passes and nothing in this document can widen them, and a spend \
         that exceeds one is aborted."
            .into(),
        String::new(),
        "Nothing on the chain checks a destination, a protocol, an asset, or a recipient. Those \
         limits are pre-flight, and the refusal is the signer's: it reads them from the run-set it \
         loaded and will not sign a transaction that breaks one. That is a real refusal and a \
         different one, and it is worth knowing which you are relying on."
            .into(),
        String::new(),
        "The slippage floor is pre-flight too, and enforced twice: the signer refuses to sign an \
         envelope whose guard call does not match the floor it was given, and the chain aborts the \
         transaction if the floor is breached once it runs."
            .into(),
    ]);

    Step {
        heading: "Which layer holds which limit",
        lines,
    }
}

/// Step five, when there is a grant to describe. Values and labels both come from the manifest's
/// one declaration producer, so this table and the wallet read cannot disagree.
fn grant_step(manifest: Option<&CapabilityManifest>) -> Option<Step> {
    let Some(manifest) = manifest else {
        return Some(Step {
            heading: "What this wallet grants",
            lines: vec![
                "No agent wallet is bound here yet, so no spend limit is attached and nothing \
                 would refuse an amount. That is the state, not a default to read past."
                    .into(),
                String::new(),
                "Ask the owner to attach a capability manifest (a budget, a per-transaction cap, a \
                 rate limit, a time window, and the pre-flight scopes the signer refuses against) \
                 before running this unattended."
                    .into(),
            ],
        });
    };

    let declaration = match to_declaration(manifest) {
        Ok(declaration) => declaration,
        // A manifest that does not validate has no honest rendering: printing the rules it claims
        // would describe limits that were never attachable. Say which check it failed instead.
        Err(error) => {
            return Some(Step {
                heading: "What this wallet grants",
                lines: vec![format!(
                    "This wallet's manifest does not validate, so no grant can be stated: \
                     {error}. Nothing is bounded until it does."
                )],
            })
        }
    };

    let mut lines = vec![
        "The owner granted this agent exactly the following. The layer column is the one that \
         refuses, not a restatement of the first:"
            .into(),
        String::new(),
        "| Grant | Value | Layer | What refuses |".into(),
        "|---|---|---|---|".into(),
    ];
    for cap in &declaration.caps {
        lines.push(format!(
            "| {} | {} | {} | {} |",
            cap.label,
            cap.value,
            cap.enforcement.as_str(),
            cap.enforcement.enforced_by()
        ));
    }
    lines.extend([
        String::new(),
        "Anything outside this is refused, and the row says by whom. Do not work around a \
         refusal: raise it with the owner, who is the only one who can widen a rule."
            .into(),
    ]);

    Some(Step {
        heading: "What this wallet grants",
        lines,
    })
}

/// The last step, and the only one that is a sentence for a human to copy.
fn prompt_step(manifest: Option<&CapabilityManifest>) -> Option<Step> {
    let prompt = if manifest.is_some() {
        "Using the rill-actions and rill-wallet MCP servers, list the available actions, describe \
         the one I name, then build it and execute it inside the grant above. Stop and ask me \
         before anything that would exceed it."
    } else {
        "Using the rill-actions and rill-wallet MCP servers, list the available actions and \
         describe the one I name, then tell me what a wallet grant would have to allow before you \
         build anything. Do not execute until one is attached."
    };
    Some(Step {
        heading: "Then you just prompt",
        lines: vec![format!("> \"{prompt}\"")],
    })
}

/// The one claim a reader can check for themselves in a single command.
///
/// Not numbered, because it is not a step in the setup. It is here because every other sentence
/// above asks the reader to believe something about where the key is.
fn keyless_check(config: &Config) -> Vec<String> {
    let base = config.public_base_url.trim_end_matches('/');
    vec![
        "## Checking the builder holds no key".into(),
        String::new(),
        "```bash".into(),
        format!("curl -fsS {base}/health"),
        "```".into(),
        String::new(),
        format!(
            "`keyless` is a field in that answer, and the thing behind it is the absence of a \
             route: this deployment offers the build tools above and nothing that signs or submits. \
             What it returns is an unsigned envelope, and the only thing that turns one into a \
             transaction is the binary on your own machine. The same check against the tool list: \
             no tool on `{}` is marked destructive.",
            config.resource()
        ),
    ]
}

/// The first sentence of a tool's own description.
///
/// The description is the producer's and is written for an agent reading `tools/list`; its first
/// sentence is what the tool is for. Taking it rather than writing a gloss here means the document
/// cannot describe a tool as something it has stopped being.
fn summary(tool: &Tool) -> String {
    let description = tool.description.as_deref().unwrap_or_default();
    let first = match description.find(". ") {
        Some(end) => &description[..=end],
        None => description,
    };
    let mut text = first.trim().to_owned();
    // From the annotation, not from the prose: a client decides whether to stop and ask a human
    // from this flag, and a reader of the document deserves the same warning.
    if tool
        .annotations
        .as_ref()
        .and_then(|a| a.destructive_hint)
        .unwrap_or(false)
    {
        text.push_str(" Submits a real transaction, and it cannot be undone.");
    }
    text
}

/// Whether a tool takes an `actionId`, so the document can fill in the published action's id.
fn takes_action_id(tool: &Tool) -> bool {
    required_arguments(tool).any(|name| name == "actionId")
}

/// The signer's tool that a built envelope is handed to: the one whose arguments take an envelope.
///
/// Found rather than named. A renamed tool then drops out of the document and the test fails,
/// instead of the document going on telling agents to call something that is not there, which is
/// what the reference does today with `execute_rill_action`.
fn envelope_tool(local: &[Tool]) -> Option<&Tool> {
    local
        .iter()
        .find(|tool| required_arguments(tool).any(|name| name == "envelope"))
}

/// The names a tool's schema requires.
fn required_arguments(tool: &Tool) -> impl Iterator<Item = &str> {
    tool.input_schema
        .get("required")
        .and_then(|value| value.as_array())
        .map(|names| names.as_slice())
        .unwrap_or_default()
        .iter()
        .filter_map(|name| name.as_str())
}
