//! The HTTP surface.
//!
//! # CORS
//!
//! `Authorization` and `MCP-Protocol-Version` must be **allowed** or the browser preflight fails
//! before a request is ever seen here — which looks like an unreachable server rather than a CORS
//! rejection. `WWW-Authenticate` must be **exposed**, not merely allowed: it carries the discovery
//! pointer a client reads off a 401 to find the authorization server, and an unexposed response
//! header is invisible to browser JavaScript.

use axum::extract::{DefaultBodyLimit, Path, State};
use axum::http::{header, HeaderValue, Method, StatusCode};
use axum::response::Response;
use axum::routing::{get, post};
use axum::Router;
use rill_store::SkillStore;
use serde_json::{json, Value};
use tower_http::cors::{Any, CorsLayer};

use crate::envelope::{api_err, api_ok, bare};
use crate::state::AppState;

/// The frontend hard-caps its own requests, and this caps the other direction. 512 KB is far more
/// than any flow graph and far less than a memory problem.
const MAX_BODY_BYTES: usize = 512 * 1024;

pub fn router(state: AppState) -> Router {
    let cors = CorsLayer::new()
        .allow_origin(Any)
        .allow_methods([Method::GET, Method::POST, Method::OPTIONS])
        .allow_headers([
            header::CONTENT_TYPE,
            header::AUTHORIZATION,
            HeaderValue::from_static("mcp-protocol-version")
                .to_str()
                .unwrap()
                .parse()
                .unwrap(),
        ])
        .expose_headers([
            header::WWW_AUTHENTICATE,
            HeaderValue::from_static("mcp-protocol-version")
                .to_str()
                .unwrap()
                .parse()
                .unwrap(),
        ])
        .max_age(std::time::Duration::from_secs(600));

    Router::new()
        // Bare JSON, no envelope — the container healthcheck and the frontend both read this.
        .route("/health", get(health))
        // Discovery must live at the origin root. See the module note in main.rs.
        .route(
            "/.well-known/oauth-protected-resource",
            get(protected_resource_metadata),
        )
        .route(
            "/.well-known/oauth-protected-resource/mcp",
            get(protected_resource_metadata),
        )
        .route(
            "/.well-known/oauth-authorization-server",
            get(authorization_server_metadata),
        )
        .route(
            "/.well-known/oauth-authorization-server/mcp",
            get(authorization_server_metadata),
        )
        // A browser landing here gets the docs; an MCP client probing for a server-push stream
        // gets 405, which its SDK understands. Both answers come before any auth check, because
        // making discovery require a token is how a connector becomes unaddable.
        .route("/mcp", get(mcp_get).post(mcp_post))
        // The four addresses the discovery document has always named. Until now none of them
        // existed, so a client that respected discovery — the point of discovery — got a 404.
        .route("/oauth/register", post(crate::oauth_routes::register))
        .route("/oauth/authorize", get(crate::oauth_routes::authorize))
        .route("/oauth/token", post(crate::oauth_routes::token))
        .route("/oauth/revoke", post(crate::oauth_routes::revoke))
        // The document this server hands agents, generated by this server. `/mcp` has always
        // redirected a browser here; until now nothing answered.
        .route("/api/docs", get(crate::agent_docs::docs))
        .route("/api/skills", get(list_skills).post(publish_skill))
        .route("/api/skills/{id}", get(get_skill))
        .route(
            "/api/skills/{id}/instructions.md",
            get(crate::agent_docs::skill_instructions),
        )
        .route("/api/protocols", get(protocols))
        .route("/api/introspect", post(introspect))
        .layer(DefaultBodyLimit::max(MAX_BODY_BYTES))
        .layer(cors)
        .with_state(state)
}

async fn health(State(state): State<AppState>) -> Response {
    bare(json!({
        "status": "ok",
        "network": state.config.network.as_str(),
        "keyless": true,
        "docs": state.config.base(),
        "mcp": {
            "endpoint": state.config.resource(),
            "auth": "oauth2.1+pkce+dcr",
            // Whether issued tokens survive a restart. An operator can see at a glance whether
            // this deployment is running on an ephemeral secret. It still answers exactly that
            // question and nothing more: an agent credential additionally needs the file at
            // OAUTH_STORE_PATH to survive, because its revocation handle lives there, so a
            // deployment issuing them must mount a volume.
            "tokensDurable": state.config.oauth_secret_from_env,
            // Whether this deployment can mint the long-lived credential a browserless agent
            // needs. Reported because the grant is otherwise invisible until someone calls it and
            // reads the refusal.
            "agentCredentials": state.config.issues_agent_credentials(),
        },
        "skills": state.skills.count(),
    }))
}

/// RFC 9728. Points a client that got a 401 at the authorization server it should use.
async fn protected_resource_metadata(State(state): State<AppState>) -> Response {
    bare(json!({
        "resource": state.config.resource(),
        "authorization_servers": [state.config.base()],
        "bearer_methods_supported": ["header"],
        "scopes_supported": rill_auth::oauth::SUPPORTED_SCOPES,
    }))
}

/// RFC 8414. What an MCP client fetches to learn where to register, authorize, and get tokens.
async fn authorization_server_metadata(State(state): State<AppState>) -> Response {
    let base = state.config.base();
    bare(json!({
        "issuer": base,
        "authorization_endpoint": format!("{base}/oauth/authorize"),
        "token_endpoint": format!("{base}/oauth/token"),
        "registration_endpoint": format!("{base}/oauth/register"),
        "revocation_endpoint": format!("{base}/oauth/revoke"),
        "response_types_supported": ["code"],
        // The agent-credential grant is named only where it is configured. Advertising a grant this
        // deployment would refuse is the same failure as advertising an endpoint that 404s.
        "grant_types_supported": grant_types(&state),
        // S256 only. OAuth 2.1 removes `plain`, which protects nothing against anyone who can
        // observe the authorization request.
        "code_challenge_methods_supported": [rill_auth::oauth::CODE_CHALLENGE_METHOD],
        // Public clients only — a secret shipped to a desktop agent is not a secret.
        "token_endpoint_auth_methods_supported": ["none"],
        "scopes_supported": rill_auth::oauth::SUPPORTED_SCOPES,
        "resource_indicators_supported": true,
    }))
}

/// The grants this deployment will actually honour.
fn grant_types(state: &AppState) -> Vec<&'static str> {
    let mut grants = vec!["authorization_code", "refresh_token"];
    if state.config.issues_agent_credentials() {
        grants.push(crate::oauth_routes::AGENT_TOKEN_GRANT);
    }
    grants
}

async fn mcp_get(State(state): State<AppState>) -> Response {
    // This server never pushes, so there is no event stream to open.
    (
        StatusCode::SEE_OTHER,
        [(
            header::LOCATION,
            format!("{}/api/docs", state.config.base()),
        )],
    )
        .into_response()
}

use axum::response::IntoResponse as _;

/// The owner-scoped MCP endpoint. Every 401 carries `WWW-Authenticate` so a client can discover
/// where to authenticate rather than reporting a dead connector.
async fn mcp_post(
    State(state): State<AppState>,
    headers: axum::http::HeaderMap,
    body: axum::body::Bytes,
) -> Response {
    let authorization = headers
        .get(header::AUTHORIZATION)
        .and_then(|v| v.to_str().ok());
    crate::mcp::post(state, authorization, body).await
}

/// What you see depends on who you are. Without a token, only skills that have no owner —
/// everything published before ownership existed. A skill id is enough to build against that
/// skill's wallet binding on the public per-skill endpoint, so once ids belong to people,
/// enumerating them all is a real leak rather than a cosmetic one.
/// `POST /api/skills`: publish an action the authenticated owner can then build.
///
/// # Why this had to exist
///
/// `SkillStore::save` had only test callers. Nothing in the running server ever wrote a skill, so
/// `rill_list_actions` answered `{"actions":[]}` for every caller forever and the two tools that take
/// an `actionId` could never succeed against one. The whole keyless build surface, the OAuth server in
/// front of it and the owner-scoped catalogue behind it were reachable and had nothing to reach.
///
/// # The owner comes from the token and nowhere else
///
/// `SkillStore::list_by_owner` is documented as "an authorization boundary, and it is the only thing
/// between one user's catalogue and another's". A publish that took the owner from the body would be
/// the other side of that boundary handing itself an address. So the owner is the authenticated
/// subject, and a body that carries `owner` or `id` is **refused** rather than having the field
/// ignored: a caller whose `owner` was silently dropped believes it published for someone else, and
/// finds out when that someone cannot see it.
///
/// # What a published action currently is
///
/// A named grant, not a description of a transaction. `rill_build_action` checks that the id is in the
/// caller's catalogue and then builds the one shape this server builds, a DeepBook limit order, from
/// the request's own parameters. `flow` is stored for the canvas and is not read when building, so a
/// flow describing something else would not change what is built. That is stated here because the
/// field invites the opposite assumption.
async fn publish_skill(
    State(state): State<AppState>,
    headers: axum::http::HeaderMap,
    body: axum::body::Bytes,
) -> Response {
    let authorization = headers
        .get(axum::http::header::AUTHORIZATION)
        .and_then(|v| v.to_str().ok());
    let owner = match crate::mcp::authenticate(&state, authorization) {
        Ok(owner) => owner,
        Err(response) => return *response,
    };

    let Ok(body) = serde_json::from_slice::<Value>(&body) else {
        return api_err(StatusCode::BAD_REQUEST, "Body must be a JSON object.");
    };

    for forbidden in ["owner", "id", "createdAt", "created_at"] {
        if body.get(forbidden).is_some() {
            return api_err(
                StatusCode::BAD_REQUEST,
                format!(
                    "{forbidden} is set by the server, not by the caller. The owner is the                      authenticated subject of this token, and refusing the field is deliberate: a                      request whose {forbidden} was quietly ignored would look like it had been                      honoured."
                ),
            );
        }
    }

    let Some(name) = body
        .get("name")
        .and_then(Value::as_str)
        .filter(|n| !n.trim().is_empty())
    else {
        return api_err(
            StatusCode::BAD_REQUEST,
            "name is required and must not be blank.",
        );
    };
    let Some(description) = body
        .get("description")
        .and_then(Value::as_str)
        .filter(|d| !d.trim().is_empty())
    else {
        return api_err(
            StatusCode::BAD_REQUEST,
            "description is required and must not be blank: it is what an agent reads to decide              whether to call this action.",
        );
    };
    if name.chars().count() > MAX_SKILL_NAME_CHARS
        || description.chars().count() > MAX_SKILL_DESCRIPTION_CHARS
    {
        return api_err(
            StatusCode::BAD_REQUEST,
            format!(
                "name must be at most {MAX_SKILL_NAME_CHARS} characters and description at most                  {MAX_SKILL_DESCRIPTION_CHARS}."
            ),
        );
    }

    // A flow is optional and stored as given. An absent one is an empty graph rather than null, so a
    // reader never has to distinguish "no flow" from "a flow that failed to parse".
    let flow = body
        .get("flow")
        .cloned()
        .unwrap_or_else(|| json!({ "nodes": [], "edges": [] }));
    if let Some(issues) = flow_issues(&flow) {
        return api_err(
            StatusCode::BAD_REQUEST,
            format!("flow is not a valid graph: {issues}"),
        );
    }

    let skill = rill_store::PublishedSkill {
        id: format!("skill_{}", rill_auth::tokens::random_id()),
        name: name.to_string(),
        description: description.to_string(),
        flow,
        tool_defs: None,
        policy_id: None,
        owner: Some(owner),
        created_at: now_rfc3339(),
    };

    match state.skills.save(skill.clone()) {
        Ok(()) => api_ok(json!({
            "id": skill.id,
            "name": skill.name,
            "description": skill.description,
            "createdAt": skill.created_at,
            "note": "Published to the catalogue this token's subject owns. It is visible from \
                     rill_list_actions on the same bearer, and from no other."
        })),
        // At capacity is the caller's answer, not a server fault: the limit is deliberate.
        Err(rill_store::StoreError::AtCapacity { limit }) => api_err(
            StatusCode::CONFLICT,
            format!("This deployment stores at most {limit} actions."),
        ),
        Err(e) => api_err(StatusCode::INTERNAL_SERVER_ERROR, e.to_string()),
    }
}

/// What is wrong with a flow, if anything, as one sentence.
///
/// Validated on publish rather than on build, because a flow that cannot be a graph is a mistake the
/// publisher can still fix, while the same mistake surfacing at build time reaches an agent that did
/// not make it.
fn flow_issues(flow: &Value) -> Option<String> {
    let parsed: rill_core::flow::FlowGraph = serde_json::from_value(flow.clone()).ok()?;
    let issues = rill_core::flow::find_flow_structure_issues(&parsed);
    if issues.is_empty() {
        return None;
    }
    Some(
        issues
            .iter()
            .map(|i| i.message.clone())
            .collect::<Vec<_>>()
            .join("; "),
    )
}

fn now_rfc3339() -> String {
    let secs = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|d| d.as_secs())
        .unwrap_or(0);
    // Whole seconds, UTC, no subsecond precision: this is a creation stamp a human reads, not a
    // clock anything compares against.
    chrono_like(secs)
}

/// Seconds since the epoch as `YYYY-MM-DDTHH:MM:SSZ`, without a date dependency.
fn chrono_like(secs: u64) -> String {
    let days = secs / 86_400;
    let rem = secs % 86_400;
    let (h, m, s) = (rem / 3600, (rem % 3600) / 60, rem % 60);
    // Civil-from-days, Howard Hinnant's algorithm, which is exact for every date this will see.
    let z = days as i64 + 719_468;
    let era = if z >= 0 { z } else { z - 146_096 } / 146_097;
    let doe = (z - era * 146_097) as u64;
    let yoe = (doe - doe / 1460 + doe / 36_524 - doe / 146_096) / 365;
    let y = yoe as i64 + era * 400;
    let doy = doe - (365 * yoe + yoe / 4 - yoe / 100);
    let mp = (5 * doy + 2) / 153;
    let d = doy - (153 * mp + 2) / 5 + 1;
    let m_civil = if mp < 10 { mp + 3 } else { mp - 9 };
    let y = if m_civil <= 2 { y + 1 } else { y };
    format!("{y:04}-{m_civil:02}-{d:02}T{h:02}:{m:02}:{s:02}Z")
}

/// Caps, so one caller cannot fill the catalogue with prose.
const MAX_SKILL_NAME_CHARS: usize = 120;
const MAX_SKILL_DESCRIPTION_CHARS: usize = 2_000;

async fn list_skills(State(state): State<AppState>) -> Response {
    let visible = state.skills.list_unowned();
    let summaries: Vec<_> = visible
        .iter()
        .map(|s| {
            json!({
                "id": s.id,
                "name": s.name,
                "description": s.description,
                "createdAt": s.created_at,
            })
        })
        .collect();
    api_ok(json!({ "skills": summaries }))
}

async fn get_skill(State(state): State<AppState>, Path(id): Path<String>) -> Response {
    match state.skills.get(&id) {
        Some(skill) => api_ok(json!({
            "id": skill.id,
            "name": skill.name,
            "description": skill.description,
            "createdAt": skill.created_at,
        })),
        None => api_err(StatusCode::NOT_FOUND, "Skill not found"),
    }
}

async fn protocols(State(state): State<AppState>) -> Response {
    api_ok(json!({
        "network": state.config.network.as_str(),
        "protocols": ["deepbook_limit_order", "cetus_swap", "haedal_stake"],
    }))
}

/// Honest rather than unimplemented: the gRPC client cannot read Move bytecode or an ABI, so
/// there is nothing to introspect. Semantics come from curated manifests instead. Returning 501
/// says that; returning an empty result would imply the package had no functions.
///
/// The body is extracted and discarded on purpose. `DefaultBodyLimit` only refuses a payload when
/// something actually reads it, so a handler that ignores its body silently opts out of the cap —
/// which was not obvious until a test asked for a 413 and got a 501.
async fn introspect(_body: axum::body::Bytes) -> Response {
    api_err(
        StatusCode::NOT_IMPLEMENTED,
        "Introspection is unavailable: the gRPC client cannot read Move bytecode or ABIs. Use the \
         curated semantic manifests instead.",
    )
}
